services:
  # Base de datos PostgreSQL (igual que producci贸n)
  postgres:
    image: postgres:15-alpine
    container_name: anima-counter-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-anima_counter_dev}
      POSTGRES_USER: ${POSTGRES_USER:-anima_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - anima-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-anima_user} -d ${POSTGRES_DB:-anima_counter_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Node.js - Modo desarrollo con hot-reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: anima-counter-backend-dev
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-3000}:3000"
      - "9229:9229"  # Puerto para debug de Node.js
    networks:
      - anima-network-dev
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-anima_counter_dev}
      - DB_USER=${DB_USER:-anima_user}
      - DB_PASSWORD=${DB_PASSWORD:-dev_password}
      - PORT=${BACKEND_PORT:-3000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - LOG_LEVEL=debug
    volumes:
      # Montar c贸digo fuente para hot-reload
      - ./backend/src:/usr/src/app/src:ro
      - ./backend/package.json:/usr/src/app/package.json:ro
      # Volume para node_modules (evita sobrescribir)
      - backend_node_modules:/usr/src/app/node_modules
    command: npm run dev

  # Frontend Vue.js - Modo desarrollo con Vite HMR
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    container_name: anima-counter-frontend-dev
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    networks:
      - anima-network-dev
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-3000}
    volumes:
      # Montar c贸digo fuente para HMR (Hot Module Replacement)
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/vite.config.js:/app/vite.config.js:ro
      - ./frontend/package.json:/app/package.json:ro
      # Volume para node_modules (evita sobrescribir)
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0

  # Adminer para gesti贸n de la base de datos
  adminer:
    image: adminer:latest
    container_name: anima-counter-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - anima-network-dev
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-postgres}
      ADMINER_DESIGN: nette

volumes:
  postgres_data_dev:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  anima-network-dev:
    driver: bridge
